version: '3'
services:
  postgres:
    image: postgres:10-alpine
    env_file:
      - '.env'
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - '${POSTGRES_FILE_PATH}:/var/lib/postgresql/data'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'api'
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - postgres